#     _         _            _             _ 
#    / \  _   _| |_ ___  ___| |_ __ _ _ __| |_
#   / _ \| | | | __/ _ \/ __| __/ _` | '__| __|
#  / ___ \ |_| | || (_) \__ \ || (_| | |  | |_
# /_/   \_\__,_|\__\___/|___/\__\__,_|_|   \__|

# env
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Battery managment
exec-once = ~/.local/bin/power-auto

exec-once = awww-daemon &
exec-once = blueman-applet &
exec-once = openrgb --server &
exec-once = signal-desktop &
exec-once = vesktop --start-minimized &
exec-once = zapzap &
exec-once = kdeconnect-indicator &
exec-once = localsed &
exec-once = sleep 5; qs &
env = xcursor_size,24
env = hyprcursor_size,24
