#  ____        _
# |  _ \ _   _| | ___  ___
# | |_) | | | | |/ _ \/ __|
# |  _ <| |_| | |  __/\__ \
# |_| \_\\__,_|_|\___||___/

layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0.5

layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5
# Rofi/Waybar
layerrule = match:namespace rofi, blur on
layerrule = match:namespace rofi, ignore_alpha 0.5
layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0.5
layerrule = match:namespace selection, no_anim on
layerrule = animation popin, match:namespace rofi

# quickshell
layerrule = match:namespace quickshell, blur on
layerrule = match:namespace quickshell, ignore_alpha 0.5


# Picture in Picture
windowrule {
    name = zen-pip
    match:title = ^(Picture-in-Picture)$
    match:class = ^(zen)$

    float = true
    pin = true
    size = 640 360
    keep_aspect_ratio = true
}
