source = ~/.cache/wal/colors-hyprland.conf

# ANIMATIONS
animations {
    enabled = true
}

bezier = smoothFade, 0.25, 1, 0.5, 1

animation = fadeIn, 1, 3, linear
animation = fadeOut, 1, 3, linear
animation = inputFieldFade, 1, 2, smoothFade
animation = inputFieldWidth, 1, 3, smoothFade
animation = inputFieldDots, 1, 4, smoothFade

# AUTH
auth {
    fingerprint {
        enabled = false
        ready_message = <i>Place finger on sensor</i>
        present_message = Scanning...
        retry_delay = 250
    }
}

# GENERAL
general {
    hide_cursor = true
    fail_timeout = 2000
}

# BACKGROUND
background {
    monitor =
    path = ~/Pictures/Wallpapers/wallpaper.png
    color = $background
    blur_passes = 5
    blur_size = 7
    noise = 0.05
    contrast = 0.8916
    brightness = 0.8
    vibrancy = 0.1696
    vibrancy_darkness = 0.05
}

# Profile-Photo
image {
    monitor =
    path = ~/Pictures/Wallpapers/logo2.0.png
    size = 100
    rounding = -1
    border_size = 2
    border_color = $color8
    rotate = 0
    reload_time = -1
    reload_cmd =
    position = 0, 320
    halign = center
    valign = center
    shadow_passes = 4
    shadow_size = 6
    shadow_color = rgba(0, 0, 0, 0.5)
    shadow_boost = 1.5
}

# NAME
label {
    monitor =
    text = Sebas
    color = $foreground
    font_size = 22
    font_family = Google Sans Flex Bold
    position = 0, 240
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.4)
    shadow_boost = 1.3
}

# Hour
label {
    monitor =
    text = cmd[update:1000] date +"%I"
    color = $foreground
    font_size = 170
    font_family = Google Sans Flex Bold

    position = 0, 90
    halign = center
    valign = center
}

# Minute
label {
    monitor =
    text = cmd[update:1000] date +"%M"
    color = $foreground
    font_size = 170
    font_family = Google Sans Flex Bold

    position = 0, -90
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = $foreground
    font_size = 20
    font_family = Google Sans Flex
    position = 0, -220
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.4)
    shadow_boost = 1.3
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $color8
    inner_color = $background
    font_color = $foreground
    check_color = $color2
    fail_color = $color9
    capslock_color = $color5
    numlock_color = $color6
    fade_on_empty = true
    fade_timeout = 2000
    rounding = 20
    font_family = Google Sans Flex
    placeholder_text = <i><span foreground="##c3c6c999"> Password</span></i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> $FPRINTFAIL
    hide_input = false
    position = 0, -300
    halign = center
    valign = center
    border_size = 1
    border_color = $color8
    shadow_passes = 4
    shadow_size = 6
    shadow_color = rgba(0, 0, 0, 0.5)
    shadow_boost = 1.5
}
