#  _   _                  _                 _ 
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|
# Sebsatián Orozco Config

$mainMod = SUPER

source = ./modules/autostart.conf
source = ./modules/appearance.conf
source = ./modules/binds.conf
source = ./modules/rules.conf
source = ./modules/input.conf

# PROFILE
source = ./modules/profiles/current/profile.conf
