foreground         #F7F7F7
background         #181818
cursor             #A5A5A5

active_tab_foreground     #181818
active_tab_background     #F7F7F7
inactive_tab_foreground   #F7F7F7
inactive_tab_background   #181818

active_border_color   #F7F7F7
inactive_border_color #181818
bell_border_color     #121212

color0       #3F3F3F
color8       #A4A4A4
color1       #121212
color9       #181818
color2       #3E3E3E
color10      #535353
color3       #5D5D5D
color11      #7C7C7C
color4       #727272
color12      #989898
color5       #8E8F8F
color13      #BEBEBE
color6       #ADADAD
color14      #E7E7E7
color7       #EBEBEB
color15      #EBEBEB
